/*
 * Swagger Gjarvis - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// GjarvisAPIRouter defines the required methods for binding the api requests to a responses for the GjarvisAPI
// The GjarvisAPIRouter implementation should parse necessary information from the http request,
// pass the data to a GjarvisAPIServicer to perform the required actions, then write the service results to the http response.
type GjarvisAPIRouter interface { 
	RequestSessionId(http.ResponseWriter, *http.Request)
	SendAudio(http.ResponseWriter, *http.Request)
	SendText(http.ResponseWriter, *http.Request)
}


// GjarvisAPIServicer defines the api actions for the GjarvisAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GjarvisAPIServicer interface { 
	RequestSessionId(context.Context) (ImplResponse, error)
	SendAudio(context.Context, AudioMessage) (ImplResponse, error)
	SendText(context.Context, TextMessage) (ImplResponse, error)
}
