/*
 * Swagger Gjarvis - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"os"
)



type JarvisResponse struct {

	SessionId string `json:"sessionId,omitempty"`

	TextAnswer string `json:"textAnswer"`

	AudioAnswer *os.File `json:"audioAnswer,omitempty"`
}

// AssertJarvisResponseRequired checks if the required fields are not zero-ed
func AssertJarvisResponseRequired(obj JarvisResponse) error {
	elements := map[string]interface{}{
		"textAnswer": obj.TextAnswer,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertJarvisResponseConstraints checks if the values respects the defined constraints
func AssertJarvisResponseConstraints(obj JarvisResponse) error {
	return nil
}
