/*
 * Swagger Gjarvis - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type TextMessage struct {

	SessionId string `json:"sessionId"`

	TextMessage string `json:"textMessage"`
}

// AssertTextMessageRequired checks if the required fields are not zero-ed
func AssertTextMessageRequired(obj TextMessage) error {
	elements := map[string]interface{}{
		"sessionId": obj.SessionId,
		"textMessage": obj.TextMessage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTextMessageConstraints checks if the values respects the defined constraints
func AssertTextMessageConstraints(obj TextMessage) error {
	return nil
}
