/*
 * Swagger Gjarvis - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"os"
)



type AudioMessage struct {

	SessionId string `json:"sessionId"`

	AudioMessage *os.File `json:"audioMessage"`
}

// AssertAudioMessageRequired checks if the required fields are not zero-ed
func AssertAudioMessageRequired(obj AudioMessage) error {
	elements := map[string]interface{}{
		"sessionId": obj.SessionId,
		"audioMessage": obj.AudioMessage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAudioMessageConstraints checks if the values respects the defined constraints
func AssertAudioMessageConstraints(obj AudioMessage) error {
	return nil
}
